version: "3.8"

services:

  # ---------------- CONFIG SERVERS ----------------
  config1:
    image: mongo:7
    container_name: config1
    command: mongod --configsvr --replSet configReplSet --port 27019 --bind_ip_all
    volumes:
      - config1_data:/data/db

  config2:
    image: mongo:7
    container_name: config2
    command: mongod --configsvr --replSet configReplSet --port 27019 --bind_ip_all
    volumes:
      - config2_data:/data/db

  config3:
    image: mongo:7
    container_name: config3
    command: mongod --configsvr --replSet configReplSet --port 27019 --bind_ip_all
    volumes:
      - config3_data:/data/db


  # ---------------- SHARD 1 (3 NODES) ----------------
  shard1a:
    image: mongo:7
    container_name: shard1a
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018 --bind_ip_all
    volumes:
      - shard1a_data:/data/db

  shard1b:
    image: mongo:7
    container_name: shard1b
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018 --bind_ip_all
    volumes:
      - shard1b_data:/data/db

  shard1c:
    image: mongo:7
    container_name: shard1c
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018 --bind_ip_all
    volumes:
      - shard1c_data:/data/db


  # ---------------- SHARD 2 (3 NODES) ----------------
  shard2a:
    image: mongo:7
    container_name: shard2a
    command: mongod --shardsvr --replSet shard2ReplSet --port 27018 --bind_ip_all
    volumes:
      - shard2a_data:/data/db

  shard2b:
    image: mongo:7
    container_name: shard2b
    command: mongod --shardsvr --replSet shard2ReplSet --port 27018 --bind_ip_all
    volumes:
      - shard2b_data:/data/db

  shard2c:
    image: mongo:7
    container_name: shard2c
    command: mongod --shardsvr --replSet shard2ReplSet --port 27018 --bind_ip_all
    volumes:
      - shard2c_data:/data/db


  # ---------------- MONGOS ----------------
  mongos:
    image: mongo:7
    container_name: mongos
    depends_on:
      - config1
      - config2
      - config3
    command: >
      mongos --configdb configReplSet/config1:27019,config2:27019,config3:27019
             --bind_ip_all
    ports:
      - "27017:27017"



  # ---------------- BACKEND ----------------
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongos


  # ---------------- FRONTEND ----------------
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend


# ---------------- VOLUMES ----------------
volumes:
  config1_data:
  config2_data:
  config3_data:
  shard1a_data:
  shard1b_data:
  shard1c_data:
  shard2a_data:
  shard2b_data:
  shard2c_data: